### ISSUE TITLE
using callbacks with this SDK

### ISSUE THREAD

**Issue by juanbrujo** [MatiFace/mati-web-button#3]
How can I access callbacks such `loaded`, `userFinishedSdk` using this Web SDK?

**Comment by 1701413420** [comment]
I have the same question, in my case I am using react. Thank you.

**Comment by hmcclungiii** [comment]
There is an example of how to listen for the callbacks using plain ol' vanilla JavaScript in the [`index.html`](https://github.com/MatiFace/mati-web-button/blob/d11b2cd72be5caf780794f4c13e8303147f3cd00/index.html#L11) page, like so:
```
    // setup callbacks
    button.addEventListener('mati:loaded', ({ detail }) => {
        console.log('loaded payload', detail)
    })
    button.addEventListener('mati:userFinishedSdk', ({ detail }) => {
        console.log('finished payload', detail)
    })
    button.addEventListener('mati:exitedSdk', ({ detail }) => {
        console.log('exited payload', detail)
    })
```

**Comment by Monish-Coddle** [comment]
In my case, I have to use a callback to React.
Is there any solution to use a callback to React?

**Comment by dkchv** [comment]
will add example for react soon.

**Comment by dkchv** [comment]
here you can find example of recat with callbacks: https://codesandbox.io/s/interesting-boyd-xcg63
